{
 "title": "NIO PostgreSQL Kafka Connect",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "last id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nio_connector_last_id", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message handling duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nio_connector_handle_message_seconds_sum[1m]) / rate(nio_connector_handle_message_seconds_count[1m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "nio_connector_message_counter_total",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Messages rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(nio_connector_message_counter_total[1m])",
     "legendFormat": "count"
    }
   ]
  }
 ]
}